### PR TITLE
Fix reproducible attribute in function declarations

### LINKED ISSUE #94: zdump.c:92:66: error: standard ‘reproducible’ attribute can only be applied to function declarators or type specifiers with function type [-Werror=attributes]
I'm trying to build /opt/fil on a Gentoo system.  Like this:

````
~ # git clone https://github.com/pizlonator/fil-c.git
~ # cd optfi
~ # ./build.sh.
````

It gets a long way, but then fails with this:

````
zdump.c:92:66: error: standard ‘reproducible’ attribute can only be applied to function declarators or type specifiers with function type [-Werror=attributes]
   92 | ATTRIBUTE_REPRODUCIBLE static intmax_t delta(struct tm *, struct tm *);
      |                                                                  ^~
zdump.c:92:66: note: did you mean to specify it after ‘)’ following function parameters?
zdump.c:100:1: error: standard ‘reproducible’ attribute can only be applied to function declarators or type specifiers with function type [-Werror=attributes]
  100 | ATTRIBUTE_REPRODUCIBLE static time_t yeartot(intmax_t);
      | ^~~~~~~~~~~~~~~~~~~~~~
zdump.c:100:1: note: did you mean to specify it after ‘)’ following function parameters?
zdump.c:139:1: error: standard ‘reproducible’ attribute can only be applied to function declarators or type specifiers with function type [-Werror=attributes]
  139 | {
      | ^
zdump.c:139:1: note: did you mean to specify it after ‘)’ following function parameters?
````

I have no FLAGS in my environment.  I just did just theose three commands.

My build system:

````
kong ~l # gcc --version
gcc (Gentoo Hardened 15.2.1_p20251018 p1) 15.2.1 20251018
````

glibc version 2.42

Ideas?

### PR DESCRIPTION
**Pull request by develOseven**
Fixes #94 

Builds with gcc 15.2.1.

Don't know whether it still builds with an older compiler.
Haven't thought of a test to check that the meaning of the code hasn't changed.

### CODE REVIEW

**Review by pizlonator — APPROVED** [review]
lgtm
