### ISSUE TITLE
Postgres fails to build with Fil-C 0.67

### ISSUE THREAD

**Issue by dmityugov** [pizlonator/fil-c#54]
Hello,

I tried to build Postgres (taken straight from https://github.com/postgres/postgres) and encountered two problems. First, Fil-C is really slow, it takes awhile to compile source files, much longer than clang does this. And second, the linker produces thousand error messages about unresolved symbols. I installed Fil-C from the tar archive, as recommended, and did run setup.sh before doing anything else. The installation was on Debian 13.1 if this matters. To reproduce, check out Postgres and do these steps in its main directory:

1. `./configure CC=~/filc-0.670-linux-x86_64/build/bin/clang CXX=~/filc-0.670-linux-x86_64/build/bin/clang++ --without-readline --without-zlib --without-icu`
2. `make -j23 -ks` (both parameters are optional and should be adjusted to the hardware)

The second step eventually fails with

```
/usr/bin/ld: pg_amcheck.o: in function `Jf_main':                                                                                                                                  
pg_amcheck.c:(.text+0x539c): undefined reference to `pizlonated_PQdb'                                                                                                              
/usr/bin/ld: pg_amcheck.c:(.text+0x5741): undefined reference to `pizlonated_PQdb'                                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0x5ca5): undefined reference to `pizlonated_PQescapeIdentifier'                                                                                   
/usr/bin/ld: pg_amcheck.c:(.text+0x5ff1): undefined reference to `pizlonated_PQfreemem'                                                                                            
/usr/bin/ld: pg_amcheck.c:(.text+0x61f1): undefined reference to `pizlonated_PQresultStatus'                                                                                       
/usr/bin/ld: pg_amcheck.c:(.text+0x62aa): undefined reference to `pizlonated_PQntuples'                                                                                            
/usr/bin/ld: pg_amcheck.c:(.text+0x6363): undefined reference to `pizlonated_PQgetvalue'                                                                                           
/usr/bin/ld: pg_amcheck.c:(.text+0x6481): undefined reference to `pizlonated_PQdb'                                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0x67bd): undefined reference to `pizlonated_PQescapeIdentifier'                                                                                   
/usr/bin/ld: pg_amcheck.c:(.text+0x6d3a): undefined reference to `pizlonated_PQdb'                                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0x6edc): undefined reference to `pizlonated_PQclear'                                                                                              
/usr/bin/ld: pg_amcheck.c:(.text+0x71e2): undefined reference to `pizlonated_PQclear'                                                                                              
/usr/bin/ld: pg_amcheck.c:(.text+0x72d9): undefined reference to `pizlonated_initPQExpBuffer'                                                                                      
/usr/bin/ld: pg_amcheck.c:(.text+0x7365): undefined reference to `pizlonated_appendPQExpBufferStr'                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0x769d): undefined reference to `pizlonated_appendPQExpBuffer'                                                                                    
/usr/bin/ld: pg_amcheck.c:(.text+0x7811): undefined reference to `pizlonated_PQdb'                                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0x7d52): undefined reference to `pizlonated_appendPQExpBuffer'                                                                                    
/usr/bin/ld: pg_amcheck.c:(.text+0x7ec6): undefined reference to `pizlonated_PQdb'                                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0x8369): undefined reference to `pizlonated_appendPQExpBuffer'                                                                                    
/usr/bin/ld: pg_amcheck.c:(.text+0x9bd9): undefined reference to `pizlonated_termPQExpBuffer'                                                                                      
/usr/bin/ld: pg_amcheck.c:(.text+0x9d01): undefined reference to `pizlonated_PQgetisnull'                                                                                          
/usr/bin/ld: pg_amcheck.c:(.text+0xb64a): undefined reference to `pizlonated_PQdb'                                                                                                 
/usr/bin/ld: pg_amcheck.c:(.text+0xb6fb): undefined reference to `pizlonated_PQerrorMessage'                                                                                       
/usr/bin/ld: pg_amcheck.c:(.text+0xb989): undefined reference to `pizlonated_PQclear'                        
...
```

What might have caused this and how to fix these errors? And how to speed up the compiler if possible?

Thanks in advance for any hints

**Comment by pizlonator** [comment]
You're seeing linker errors presumably because postgres has a library that is linked with a linker script. You have two options:

1. Make the linker script refer to the Fil-C mangled symbols (i.e. `pizlonated_PQdb` instead of `PQdb`, for example).
2. Pass the linker script to clang using `--version-script=<script>` instead of using `-Wl,--version-script=<script>`. This is a way of asking my compiler to preprocess the linker scripts (which then mangles the symbols for you).

Usually (2) is the best bet.

As for the compiler being slow - it's likely possible to make it faster. I haven't put much effort into the performance of the compiler itself, yet.

**Comment by dmityugov** [comment]
That helped greatly, thanks a lot
